language: android
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
    - "git submodule update --init --recursive"
    - "git submodule sync"
    - "pushd joana"
    - "git submodule sync"
    - "popd"
script:
    - "ant"
