language: android
jdk: oraclejdk8
before_install:
    - "git submodule update --init --recursive"
    - "git submodule sync"
    - "pushd joana"
    - "git submodule sync"
    - "popd"
install:
    - "ant"


